### ISSUE TITLE
Falló la ejecución: No pudimos comunicarnos con AFIP

### ISSUE THREAD

**Issue by martinfpas** [neocomplexx/neofactura#13]
Estimados, buen dia. Dejo de funcionarme tanto en homologacion como en produccion y con distintos cuit y con distintos proveedores de internet la conexion con afip. A alguien mas le paso?

**Comment by aledc7** [comment]
Hola, recién lo probé y está funcionando bien en homologación,  tal vez sea un problema  monentaneo.

**Comment by martinfpas** [comment]
Mis disculpas. Había probado hace 5 minutos y nada. Ahi esta ok. Muchas gracias y reitero las disculpas
