### ISSUE TITLE
Error en la descripción de la implementación

### ISSUE THREAD

**Issue by ghost** [neocomplexx/neofactura#3]
Hola, antes que nada muchas gracias por compartir este proyecto, estuve haciendo algunas pruebas simples y conseguí generar mis facturas.

Te quería comentar acerca de esto: 

"La estructura esperada es un arreglo que contiene todos los campos con los mismos nombres indicados en el manual de afip"

No se si a lo mejor refactoreaste y te quedó desactualizada la documentación, pero en realidad la mayoría de los índices del array que espera el método emitirComprobante() son diferentes a los utilizados por la AFIP, ejemplo: 

> numeroDocumento / DocNro

> numeroComprobante / CbteDesde

etc.

Es muy fácil de detectar pero por ahí para alguien con poca experiencia le puede dar algún dolor de cabeza.

Un abrazo y gracias nuevamente.

Javier

**Comment by gbillot** [comment]
Buenas, excelente aporte.  Estoy tratando de generar mi primer factura pero me da el siguiente error:
Warning: Invalid argument supplied for foreach()  cuando le paso el parametro $regfac['CbtesAsoc'] = 0; dentro de $voucher.
como se pasa ese valor de CbtesAsoc  y que hay que pasar en CAEA?

Muchas gracias.  Saludos.  Guillermo

**Comment by mgesuitti** [comment]
Muy buen punto el del nombre de los campos, hay que actualizar la documentación. Prometo en la próxima versión mejorar dichas cuestiones. En breve se viene un upgrade de la librería
