### ISSUE TITLE
Error al pasar parametros

### ISSUE THREAD

**Issue by gbillot** [neocomplexx/neofactura#5]
Buenas, excelente aporte. Estoy tratando de generar mi primer factura pero me da el siguiente error:
Warning: Invalid argument supplied for foreach() cuando le paso el parametro $regfac['CbtesAsoc'] = 0; dentro de $voucher.
como se pasa ese valor de CbtesAsoc y que hay que pasar en CAEA?

Muchas gracias. Saludos. Guillermo

**Comment by mgesuitti** [comment]
¿Pudiste resolver este problema? Estoy tratando de ponerme al día con las librerías. Mil Disculpas!
