### ISSUE TITLE
Modo Homologacion para multiples clientes

### ISSUE THREAD

**Issue by pbermudez1** [neocomplexx/neofactura#8]
Estimados antes que nada felicidades por el proyecto la verdad que me ayudó mucho a la hora de desarrollar el proyecto en el que estoy trabajando.

En esta ocacion queria consultarles si alguno logró ejecutar el modo Homologacion pero para mas de un CUIT? les consulto esto porque el sistema que estoy armando la idea es que sea multiusuario (para varios clientes) y cada uno de estos tiene un CUIT diferente.

A la hora de realizar las pruebas con un cliente funciona todo de 10 ya que lo hago con los certificados que están asociados a mi CUIT, el problema es que no se como armar la configuración para un segundo cliente con un CUIT distinto. Alguien lo pudo resolver?

Muchas gracias de antemano por los aportes.

**Comment by mgesuitti** [comment]
Hola, me parece que estas mirando el problema de una forma incorrecta. 

Todas las personas que operen con vos tienen que delegarte la autorización para realizar facturación electrónica a través tuyo (Esto se hace desde sus cuentas de AFIP). Luego vos utilizas un solo certificado para todos, esa es la forma correcta.

**Comment by gbillot** [comment]
Yo modifique el código para generar una carpeta por  cuit y dentro de ellas cada punto de venta.  De esa forma puedo manejar múltiples clientes y puntos de venta en el mismo sistema. Saludos

**Comment by mgesuitti** [comment]
Perfecto, cierro la issue entonces! Saludos.

**Comment by pbermudez1** [comment]
Buenos días estimados, muchas gracias a ambos por la colaboración, probe con la autorización tal como me indico Mauro y me funciono de 10.

Muchas gracias nuevamente.
